name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  firebase_auth: ^5.1.1
  firebase_storage: ^12.1.0

  # State Management & Services
  provider: ^6.1.2
  get_it: ^7.7.0

  # Networking
  http: ^1.2.1

  # UI & Utility
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  flutter_barcode_scanner: ^2.0.0
  pdf: ^3.11.0
  printing: ^5.12.0
  intl: ^0.19.0
  
  cupertino_icons: ^1.0.6
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-variant files,
  # and are referred to from your application as such:
  # asset: assets/images/widget.png
  # images:
  #   - assets/images/widget.png

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this format:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages 