// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIZe_tMdP5zTLU9SMHV_rtQcKub5WpJrE',
    appId: '1:568498740495:web:ea13419e39956b2a33f27a',
    messagingSenderId: '568498740495',
    projectId: 'thesis-ai-pos',
    authDomain: 'thesis-ai-pos.firebaseapp.com',
    storageBucket: 'thesis-ai-pos.firebasestorage.app',
    measurementId: 'G-L39W01LLKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbJPMz-y75VaKbmOrx8j0vzIQKl1mG48g',
    appId: '1:568498740495:android:14a68f6da4547b8c33f27a',
    messagingSenderId: '568498740495',
    projectId: 'thesis-ai-pos',
    storageBucket: 'thesis-ai-pos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc4uSLiuoN2D5Y3cFPbcmNLR0uoSqgme8',
    appId: '1:568498740495:ios:b71070d8c24c35a733f27a',
    messagingSenderId: '568498740495',
    projectId: 'thesis-ai-pos',
    storageBucket: 'thesis-ai-pos.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc4uSLiuoN2D5Y3cFPbcmNLR0uoSqgme8',
    appId: '1:568498740495:ios:b71070d8c24c35a733f27a',
    messagingSenderId: '568498740495',
    projectId: 'thesis-ai-pos',
    storageBucket: 'thesis-ai-pos.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIZe_tMdP5zTLU9SMHV_rtQcKub5WpJrE',
    appId: '1:568498740495:web:0f46806b74e5a1bc33f27a',
    messagingSenderId: '568498740495',
    projectId: 'thesis-ai-pos',
    authDomain: 'thesis-ai-pos.firebaseapp.com',
    storageBucket: 'thesis-ai-pos.firebasestorage.app',
    measurementId: 'G-HNX3H9V8D0',
  );

}